#!/bin/bash

TAG=$1
MSG=$2

if [ -z "$TAG"  ]; then
	echo ""
	echo "Syntax Error: $0 <tag> <message>"
	echo ""
	exit 1
	if [ -z "$TAG" ]; then
		echo ""
        	echo "Syntax Error: $0 <tag> <message>"
        	echo ""
		exit 2
	fi
else
	git tag -a $TAG -m "$MSG"
fi
exit 0
